//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlashX.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlashX.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 View Repository 的本地化字符串。
        /// </summary>
        public static string ABOUT_VIEW_REPOSITORY {
            get {
                return ResourceManager.GetString("ABOUT_VIEW_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string DOCUMENT_TITLE_WELCOME {
            get {
                return ResourceManager.GetString("DOCUMENT_TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File(_F) 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit(_X) 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_FILE_EXIT {
            get {
                return ResourceManager.GetString("MENU_ITEM_FILE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_HELP {
            get {
                return ResourceManager.GetString("MENU_ITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About SlashX 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_HELP_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ITEM_HELP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Avalonia 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_HELP_ABOUTAVALONIA {
            get {
                return ResourceManager.GetString("MENU_ITEM_HELP_ABOUTAVALONIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_WINDOWS {
            get {
                return ResourceManager.GetString("MENU_ITEM_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Workspace 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_WINDOWS_LOAD_WORKSPACE {
            get {
                return ResourceManager.GetString("MENU_ITEM_WINDOWS_LOAD_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Workspace 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_WINDOWS_MANAGE_WORKSPACE {
            get {
                return ResourceManager.GetString("MENU_ITEM_WINDOWS_MANAGE_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Workspace 的本地化字符串。
        /// </summary>
        public static string MENU_ITEM_WINDOWS_SAVE_WORKSPACE {
            get {
                return ResourceManager.GetString("MENU_ITEM_WINDOWS_SAVE_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SlashX 的本地化字符串。
        /// </summary>
        public static string SLASHX_NAME {
            get {
                return ResourceManager.GetString("SLASHX_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string WINDOW_TITLE_ABOUT {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_ABOUT", resourceCulture);
            }
        }
    }
}
